fix unused variables
../test/platformchannel_test.c: In function 'test_raw_std_value_equals':
../test/platformchannel_test.c:758:21: error: unused variable 'str' [-Werror=unused-variable]
  758 |         const char *str = "The quick brown fox jumps over the lazy dog.";
      |                     ^~~
../test/platformchannel_test.c: In function 'test_raw_std_value_after':
../test/platformchannel_test.c:1210:21: error: unused variable 'str' [-Werror=unused-variable]
 1210 |         const char *str = "The quick brown fox jumps over the lazy dog.";
      |                     ^~~